---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure proxy
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify: restart nginx

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
    state: started
