---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart nginx

- name: Remove default Nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
    state: started
